aria:
  ros__parameters:
    serial_port: "/dev/ttyS0"
    serial_baudrate: 9600
    module_plugins: ["charger", "drive", "sonar"]
    charger:
      plugin: "pioneer_modules::Charger"
    drive:
      plugin: "pioneer_modules::Drive"
      robot_base_frame: "base_link"
      odom_frame: "odom"
      odom_topic: "odom"
      publish_tf: true
      velocity_timeout: 50000
      enable_stamped_cmd_vel: false
    sonar:
      plugin: "pioneer_modules::Sonar"
      sonar_frame: "base_link"
      sonar_topic: "sonar"
